name: NaturalDisasters-T3
main: com.tenjava.entries.PaulBGD.t3.TenJava
version: '${project.version}'

commands:
  disaster:
    usage: /disaster
    description: Opens the disaster menu, to create disasters